### ISSUE TITLE
Fresh installation return errors on first login

### ISSUE THREAD

**Issue by denisovval** [awslabs/sensitive-data-protection-on-aws#260]
### The Question

Hello team,

We deployed the admin stack via Cloudformation, it successfully deployed all required resources.
When we try to login via the portal URL, we get random errors without any context which looks like this:
![image](https://github.com/awslabs/sensitive-data-protection-on-aws/assets/129956250/f5387cb5-18e5-42f4-bc2f-21495e30e204)

Portal lamda fucntion is OK
Portal configuration lambda is OK
But we found some errors in SDPS-Admin-APIAPIFunction719F975A-G3Vu0hXVstFp lambda which we guess leads to this UI errors:

```

2023-09-07 12:00:07,165 [ERROR] exception_handler.py exception_handler() L36   Traceback (most recent call last):  File "/opt/python/requests/models.py", line 971, in json    return complexjson.loads(self.text, **kwargs)  File "/var/runtime/simplejson/__init__.py", line 525, in loads    return _default_decoder.decode(s)  File "/var/runtime/simplejson/decoder.py", line 370, in decode    obj, end = self.raw_decode(s)  File "/var/runtime/simplejson/decoder.py", line 400, in raw_decode    return self.scan_once(s, idx=_w(s, idx).end())simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/opt/python/starlette/middleware/errors.py", line 162, in __call__    await self.app(scope, receive, _send)  File "/opt/python/starlette/middleware/base.py", line 106, in __call__    response = await self.dispatch_func(request, call_next)  File "/var/task/main.py", line 87, in validate    validate_result = __validate_token(token, jwt_claims)  File "/var/task/main.py", line 119, in __validate_token    return __online_validate(token, jwt_claims)  File "/var/task/main.py", line 163, in __online_validate    json_response = requests.post(url, data, headers=headers).json()  File "/opt/python/requests/models.py", line 975, in json    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0) | 2023-09-07 12:00:07,165 [ERROR] exception_handler.py exception_handler() L36 Traceback (most recent call last): File "/opt/python/requests/models.py", line 971, in json return complexjson.loads(self.text, **kwargs) File "/var/runtime/simplejson/__init__.py", line 525, in loads return _default_decoder.decode(s) File "/var/runtime/simplejson/decoder.py", line 370, in decode obj, end = self.raw_decode(s) File "/var/runtime/simplejson/decoder.py", line 400, in raw_decode return self.scan_once(s, idx=_w(s, idx).end()) simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/python/starlette/middleware/errors.py", line 162, in __call__ await self.app(scope, receive, _send) File "/opt/python/starlette/middleware/base.py", line 106, in __call__ response = await self.dispatch_func(request, call_next) File "/var/task/main.py", line 87, in validate validate_result = __validate_token(token, jwt_claims) File "/var/task/main.py", line 119, in __validate_token return __online_validate(token, jwt_claims) File "/var/task/main.py", line 163, in __online_validate json_response = requests.post(url, data, headers=headers).json() File "/opt/python/requests/models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
-- | --

```
There are no explanations for which input data leads to this error. 

We tried to add an AWS account via agent stack but we can't see it in UI.
There are no other errors in other components according to Cloudwatch logs.

Is it a known issue? 
How can we troubleshoot this ?

### Environment

AWS organization, 
It stack deployed to delegated admin acc
Admin stack deployed to the same delegated admin acc
Agent stack deployed to another aws acc
We use latest version of stack

### Other information

Enabled DEBUG for API lambda and it complains about TOKEN:

```
2023-09-07 13:07:27,690 [DEBUG] main.py validate() L86 token not in list
--
```
 

<br class="Apple-interchange-newline">

**Comment by denisovval** [comment]
Okay, the issue was with OIDC provider which is OKTA and it has an incorrect URL.

I propose to add logging to _online_validate function, so it will complain if OIDC url is incorrect
